# version: "2"
# services:
#   app:
#     container_name: app
#     restart: always
#     build: .
#     ports:
#       - "4000:4000"
#     links:
#       - mongo
#   mongo:
#     container_name: mongo
#     image: mongo
#     volumes:
#       - ./data:/data/db
#     ports:
#       - "27017:27017"

version: "3"
#qitu e ki FRONTIN
services:
  app:
    build: ./app
    ports:
       - 8080:8080
    volumes:
      - ./app:/data
    environment:
      - API_URL=http://localhost:8081/

#qitu e ki Serverin
  server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/data
    depends_on: 
      - server-database
    environment:
      - DATABASE_URL=server-database:27017
  
      #qitu e ki Databazen ,kto krejt jan trujtem ne DockerHub , SourceCode
      #Si krejt sourceCode qe jan trujtne , edhe kjo me imell tanin .

  server-database:
    image: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db